### ISSUE TITLE
Live Demo

### ISSUE THREAD

**Issue by austinkregel** [devplanete/php-login-advanced#25]
Hia, I decided I loved the project so much that I threw up a demo over on my website http://php-login.austinkregel.com , it truncates the database every other week.

Also, you're missing the `if($this->databaseConnection()){ ... }` in the `registerNewUser(...)` function.

**Comment by ace2go** [comment]
I keep on getting "Verification Mail NOT successfully sent! Error: SMTP connect() failed." and have no idea why....

**Comment by austinkregel** [comment]
If you don't mind me asking, what was the user information you put in (minus the password)? 

I'm taking a look at my server and I don't see any errors popping up.

**Comment by austinkregel** [comment]
From what i can see, it will only error out if it couldn't send the verification email. Make your you double check the email you're inputting, to make sure it's the proper email.

**Comment by ace2go** [comment]
define("EMAIL_USE_SMTP", true);
define("EMAIL_SMTP_HOST", "ssl://smtp.gmail.com");
define("EMAIL_SMTP_AUTH", true);
define("EMAIL_SMTP_USERNAME", "7shadymonkeys@gmail.com");
define("EMAIL_SMTP_PASSWORD", "take your best guess ;)");
define("EMAIL_SMTP_PORT", 465);
define("EMAIL_SMTP_ENCRYPTION", "ssl");

**Comment by charlesterrill** [comment]
Dear Austin,Your script is great. I just don't know how to install it. I have included a text file that should give you the breakdown on what I have. 
Thanks so much,Charles  Charles Terrill
Passionate Inventor and Mentor 

CHT4 Innovation Labs, One Broadway 14th Floor, Cambridge, MA 02142  (617) 252-8723
charles.terrill@cht4.com    http://www.cht4.com  @CharlesTerrill on Twitter

CHT4 Innovation Labs is located at the Cambridge Innovation Center at Kendall Square

**Comment by austinkregel** [comment]
Charles, I strongly recommend removing that comment and replying to my email directly. 
Thank you.

**Comment by austinkregel** [comment]
One final question from me before I depart for a few hours.
    Did you download devplanete's fork of the advanced login script or my fork of the script?
When I have a free moment, I will try it on my server, but currently I am very busy.

**Comment by devplanete** [comment]
"Error: SMTP connect() failed." generally says that the port 465 is blocked in the hosting webserver.

**Comment by ace2go** [comment]
Thank you so much devplanete - that was the issue with the SMTP Connect error.  Now I just have to figure out why it will not let me access index.php from logging on, I keep on getting the following message : "Forbidden
You don't have permission to access /index.php on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request."
