### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by Niknox** [devplanete/php-login-advanced#30]
Hey,

very nice that you continue the advanced version.

I'd be very happy to translate it to German if you want and allow.

**Comment by devplanete** [comment]
Hello,
Of course you are welcome on board. And I'm sure that a German translation will be appreciate.

**Comment by devplanete** [comment]
It's in the develop branch.
For testing for a few days and waiting for commit to master branch

**Comment by Niknox** [comment]
Copy that.
