### ISSUE TITLE
FIle doesn't exist to verify user email

### ISSUE THREAD

**Issue by Wargog** [devplanete/php-login-advanced#37]
The verify email sends the user an email with a link to register.php with the verification code, problem being that file doesn't exist. https://a3panel.omacostudio.com/register.php?id=4&verification_code=f20c686f28042061302ac6b130e604296611894d leads to a 404

**Comment by devplanete** [comment]
Please, update to the last version of php-login-advanced
Since a few releases, there is no more register.php file.

The entry point for all requests of the application is the index.php
