### ISSUE TITLE
Can't understand few sections

### ISSUE THREAD

**Issue by uzumakifahim** [devplanete/php-login-advanced#39]
Hi,

I admit that, this is an excellent script with really good documentation. But maybe due to my inexperience with PHP and MySQL, I can't successfully make this work. I think you guys here can help me to overcome this issues.

1. In the documentation at the "basic config" section. It is mentioned that, in the config/config.php file, I need to change “EMAIL_PASSWORDRESET_URL” and “EMAIL_VERIFICATION_URL” according my needs. But unfortunately, I can't find anything like this “EMAIL_PASSWORDRESET_URL” and “EMAIL_VERIFICATION_URL” in the config.php file.

2. In the "php-login-advanced-master" file, I can't find any classes folder and also classes/Registration.php and classes/Login.php. But according to the "Edit the email SMTP configs" of the documentation, I need to edit these files.

3. I'm testing this script on my Ubuntu 14.04 machine at my home. So there is no specific website URL. In that case, according to the documentation, when I write "localhost" in the address bar and press enter, the desired login page is not appears.

Please help me guys. I know you've done it many times.
Thanks in advance.

**Comment by devplanete** [comment]
Hi,

1. “EMAIL_PASSWORDRESET_URL” and “EMAIL_VERIFICATION_URL” are not used anymore (I have to update the doc...)

2. "classes/Registration.php" and "classes/Login.php" have been merged into PHPLogin.php

3. are you sure that you apache webserver is running?
