### ISSUE TITLE
Invalid cookie

### ISSUE THREAD

**Issue by pippuccio76** [devplanete/php-login-advanced#49]
Hi in  a page , i do this :
`
<?php  
list ($user_id, $token, $hash) = explode(':', $_COOKIE['rememberme']);
echo $hash.'<br>';
echo hash('sha256', $user_id . ':' . $token . COOKIE_SECRET_KEY).'<br>';
echo $token.'<br>';

?>
`

this is the result :
`
e29d5f96be49274b6d4050d702387068439492b71803142c694b45020d4484ba
e29d5f96be49274b6d4050d702387068439492b71803142c694b45020d4484ba
20fca1f7a106ae8def6964a04c474851b8ae964390e3a97f134f78f40eeddc4e
`

But i have Invalid cookie , why ?

**Comment by devplanete** [comment]
??
